import type { AlertCategory, AlertPriority } from "@/lib/types";

/** FUD, hype y ruido retail cripto — bloqueo total */
export const NOISE_PATTERNS = [
  /\b(moon|lambo|wagmi|ngmi|gm\b|wen\s|to\s+the\s+moon|100x|pump\s+it|rekt)\b/i,
  /\b(airdrop|giveaway|nft\s+mint|memecoin|shitcoin)\b/i,
  /\b(not\s+financial\s+advice|nfa\b|dyor)\b/i,
  /\b(breaking\s*:\s*elon|just\s+in:\s*elon)\b/i,
  /\b(gm frens|good morning ct|crypto twitter)\b/i,
  /\b(altseason|alt season|pumpamentals)\b/i,
  /\b(scam|rug\s*pull|rugpull|ponzi)\b/i,
  /\b(crash\s+incoming|imminent\s+crash|btc\s+to\s+zero)\b/i,
];

/** Hype/pánico sin datos — solo emocional */
export const CRYPTO_FUD_HYPE = [
  /\b(to the moon|moon\s+soon|1000x|guaranteed\s+returns)\b/i,
  /\b(crash|capitulation|blood\s+in\s+the\s+streets)\b/i,
];

export const CATEGORY_KEYWORDS: Record<
  AlertCategory,
  { terms: string[]; priority: AlertPriority }
> = {
  fed: {
    terms: [
      "federal reserve",
      "fomc",
      "interest rate",
      "rate cut",
      "rate hike",
      "powell",
      "monetary policy",
      "fed funds",
      "basis points",
      "quantitative tightening",
      "quantitative easing",
      "dot plot",
      "jackson hole",
      "emergency meeting",
      "unscheduled speech",
      "warsh",
      "hawkish",
      "dovish",
    ],
    priority: "critical",
  },
  macro: {
    terms: [
      "cpi",
      "core cpi",
      "ppi",
      "core pce",
      "pce",
      "inflation",
      "nonfarm",
      "non-farm",
      "payroll",
      "nfp",
      "employment",
      "unemployment",
      "jobless",
      "gdp",
      "consumer price",
      "producer price",
      "labor market",
      "retail sales",
      "ism manufacturing",
      "ism services",
      "pmi manufacturing",
      "pmi services",
      "consumer confidence",
      "dxy",
      "dollar index",
      "u.s. dollar index",
      "tips",
      "real yield",
      "treasury yield",
      "10-year",
      "10 year",
      "cot report",
      "commitment of traders",
      "gld",
      "gold etf",
      "etf flow",
      "xau",
      "spot gold",
      "bullion",
      "gold price",
    ],
    priority: "critical",
  },
  geopolitics: {
    terms: [
      "armed conflict",
      "military strike",
      "air strike",
      "airstrike",
      "missile strike",
      "missile attack",
      "invasion",
      "declared war",
      "state of war",
      "major sanctions",
      "energy infrastructure",
      "nuclear threat",
      "ceasefire broken",
      "safe haven",
      "gold safe haven",
      "geopolitical shock",
      "escalation",
      "embargo",
      "iran",
      "tehran",
      "irgc",
      "strait of hormuz",
      "hormuz",
      "counterattack",
      "counter-attack",
      "retaliation",
      "drone strike",
      "ballistic missile",
      "ataque militar",
      "contraataque",
      "represalia",
    ],
    priority: "critical",
  },
  btc_whale: {
    terms: [
      "whale",
      "large transfer",
      "massive transfer",
      "exchange inflow",
      "exchange outflow",
      "cold wallet",
      "institutional flow",
      "etf inflow",
      "etf outflow",
      "spot etf flow",
      "glassnode",
      "cryptoquant",
    ],
    priority: "high",
  },
  btc_regulation: {
    terms: [
      "securities and exchange",
      "sec charges",
      "sec sues",
      "sec approval",
      "cftc",
      "spot bitcoin etf",
      "bitcoin etf",
      "etf approval",
      "enforcement action",
      "exchange hack",
      "exchange bankruptcy",
      "custodian",
      "crypto ban",
      "regulatory action",
    ],
    priority: "critical",
  },
};

/** Eventos que elevan a CRÍTICO instantáneo (con fuente verificada) */
export const CRITICAL_EVENT_TERMS = [
  "fomc",
  "rate decision",
  "fed funds",
  "nonfarm",
  "non-farm",
  "nfp",
  "cpi",
  "core cpi",
  "core pce",
  "pce",
  "powell press",
  "emergency",
  "exchange hack",
  "bankruptcy",
  "etf approval",
  "spot etf",
  "invasion",
  "military strike",
  "air strike",
  "airstrike",
  "missile strike",
  "missile attack",
  "major sanctions",
  "strait of hormuz",
  "hormuz",
  "counterattack",
  "counter-attack",
  "retaliation",
  "drone strike",
  "ballistic missile",
  "ataque militar",
  "contraataque",
  "represalia",
];

export const CRITICAL_BOOST_TERMS = [
  "breaking",
  "urgent",
  "surprise",
  "unexpected",
  "beats consensus",
  "misses consensus",
  "vs consensus",
  "vs. consensus",
  "deviation",
  "shock",
];

/** Términos para fingerprint de deduplicación */
export const EVENT_FINGERPRINT_TERMS = [
  ...CRITICAL_EVENT_TERMS,
  "dxy",
  "tips",
  "real yield",
  "whale",
  "etf",
  "sec",
  "cftc",
  "war",
  "sanctions",
  "pmi",
  "gdp",
];
