import type { AlertCategory, AlertPriority } from "@/lib/types";

export const NOISE_PATTERNS = [
  /\b(moon|lambo|wagmi|ngmi|gm\b|wen\s|to\s+the\s+moon|100x|pump\s+it|rekt)\b/i,
  /\b(airdrop|giveaway|nft\s+mint|memecoin|shitcoin)\b/i,
  /\b(not\s+financial\s+advice|nfa\b|dyor)\b/i,
  /\b(breaking\s*:\s*elon|just\s+in:\s*elon)\b/i,
];

export const CATEGORY_KEYWORDS: Record<
  AlertCategory,
  { terms: string[]; priority: AlertPriority }
> = {
  fed: {
    terms: [
      "federal reserve",
      "fomc",
      "interest rate",
      "rate cut",
      "rate hike",
      "powell",
      "monetary policy",
      "tasa de interés",
      "tasas de interés",
      "política monetaria",
      "fed funds",
      "basis points",
      "quantitative tightening",
      "quantitative easing",
      "dot plot",
      "jackson hole",
    ],
    priority: "critical",
  },
  macro: {
    terms: [
      "cpi",
      "ppi",
      "inflation",
      "inflación",
      "nonfarm",
      "non-farm",
      "payroll",
      "employment",
      "unemployment",
      "jobless",
      "gdp",
      "pce",
      "consumer price",
      "producer price",
      "nfp",
      "empleo",
      "desempleo",
      "labor market",
      "retail sales",
      "ism manufacturing",
    ],
    priority: "critical",
  },
  geopolitics: {
    terms: [
      "war",
      "conflict",
      "sanctions",
      "sanciones",
      "geopolitical",
      "middle east",
      "ukraine",
      "israel",
      "iran",
      "taiwan",
      "nuclear",
      "invasion",
      "ceasefire",
      "gold safe haven",
      "safe haven",
      "refugio",
      "tension",
      "military",
      "strike",
      "embargo",
    ],
    priority: "high",
  },
  btc_whale: {
    terms: [
      "whale",
      "large transfer",
      "massive transfer",
      "moved",
      "btc transferred",
      "bitcoin transferred",
      "exchange inflow",
      "exchange outflow",
      "cold wallet",
      "ballena",
      "transferencia masiva",
    ],
    priority: "high",
  },
  btc_regulation: {
    terms: [
      "sec",
      "cftc",
      "regulation",
      "regulación",
      "etf",
      "blackrock",
      "fidelity",
      "grayscale",
      "institutional",
      "institucional",
      "legislation",
      "legislación",
      "crypto bill",
      "bitcoin etf",
      "spot etf",
      "enforcement",
      "fine",
      "multa",
      "approval",
      "aprobación",
    ],
    priority: "critical",
  },
};

export const CRITICAL_BOOST_TERMS = [
  "breaking",
  "urgent",
  "emergency",
  "surprise",
  "unexpected",
  "rate decision",
  "fomc statement",
  "jobs report",
];
