import type { FeedSource } from "@/lib/types";

/** Solo fuentes institucionales verificadas */
export const FEED_SOURCES: FeedSource[] = [
  {
    id: "fed-press",
    name: "Federal Reserve",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    type: "rss",
    credibility: 10,
    categories: ["fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "fed-speeches",
    name: "Fed — Discursos",
    url: "https://www.federalreserve.gov/feeds/speeches.xml",
    type: "rss",
    credibility: 10,
    categories: ["fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "bls-news",
    name: "BLS — Empleo e inflación",
    url: "https://www.bls.gov/feeds/news_release.rss",
    type: "rss",
    credibility: 10,
    categories: ["macro"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "bea-news",
    name: "BEA — Datos macro",
    url: "https://www.bea.gov/rss.xml",
    type: "rss",
    credibility: 10,
    categories: ["macro"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "reuters-markets",
    name: "Reuters — Mercados",
    url: "https://feeds.reuters.com/reuters/marketsNews",
    type: "rss",
    credibility: 10,
    categories: ["fed", "macro", "geopolitics"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "reuters-business",
    name: "Reuters — Negocios",
    url: "https://feeds.reuters.com/reuters/businessNews",
    type: "rss",
    credibility: 10,
    categories: ["macro", "geopolitics"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "sec-press",
    name: "SEC — Comunicados",
    url: "https://www.sec.gov/news/pressreleases.rss",
    type: "rss",
    credibility: 10,
    categories: ["btc_regulation"],
    assets: ["BTC"],
    enabled: true,
  },
  {
    id: "cftc-press",
    name: "CFTC — Regulación",
    url: "https://www.cftc.gov/rss/pressreleases.xml",
    type: "rss",
    credibility: 10,
    categories: ["btc_regulation"],
    assets: ["BTC"],
    enabled: true,
  },
  // Fallback Nitter — solo activo si el navegador de X no tiene sesión
  {
    id: "nitter-federalreserve",
    name: "X — @federalreserve",
    url: "https://nitter.poast.org/federalreserve/rss",
    type: "twitter_rss",
    credibility: 10,
    categories: ["fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "nitter-reuters",
    name: "X — @Reuters",
    url: "https://nitter.poast.org/Reuters/rss",
    type: "twitter_rss",
    credibility: 10,
    categories: ["macro", "geopolitics", "fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "nitter-business",
    name: "X — @business",
    url: "https://nitter.poast.org/business/rss",
    type: "twitter_rss",
    credibility: 10,
    categories: ["macro", "geopolitics", "btc_regulation"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "nitter-fxstreet",
    name: "X — @FXStreet",
    url: "https://nitter.poast.org/FXStreet/rss",
    type: "twitter_rss",
    credibility: 9,
    categories: ["macro", "fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "nitter-whale-alert",
    name: "X — @whale_alert",
    url: "https://nitter.poast.org/whale_alert/rss",
    type: "twitter_rss",
    credibility: 9,
    categories: ["btc_whale"],
    assets: ["BTC"],
    enabled: true,
  },
  {
    id: "nitter-sec",
    name: "X — @SEC_News",
    url: "https://nitter.poast.org/SEC_News/rss",
    type: "twitter_rss",
    credibility: 10,
    categories: ["btc_regulation"],
    assets: ["BTC"],
    enabled: true,
  },
  {
    id: "nitter-ecb",
    name: "X — @ecb",
    url: "https://nitter.poast.org/ecb/rss",
    type: "twitter_rss",
    credibility: 10,
    categories: ["fed", "macro"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
];
