import type { FeedSource } from "@/lib/types";

/** Fuentes institucionales y financieras — sin cuentas secundarias ni agregadores ruidosos */
export const FEED_SOURCES: FeedSource[] = [
  {
    id: "fed-press",
    name: "Federal Reserve",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    type: "rss",
    credibility: 10,
    categories: ["fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "fed-speeches",
    name: "Fed — Discursos",
    url: "https://www.federalreserve.gov/feeds/speeches.xml",
    type: "rss",
    credibility: 10,
    categories: ["fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "bls-news",
    name: "BLS — Empleo e inflación",
    url: "https://www.bls.gov/feeds/news_release.rss",
    type: "rss",
    credibility: 10,
    categories: ["macro"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "bea-news",
    name: "BEA — Datos macro",
    url: "https://www.bea.gov/rss.xml",
    type: "rss",
    credibility: 10,
    categories: ["macro"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "reuters-markets",
    name: "Reuters — Mercados",
    url: "https://feeds.reuters.com/reuters/marketsNews",
    type: "rss",
    credibility: 9,
    categories: ["fed", "macro", "geopolitics"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "reuters-business",
    name: "Reuters — Negocios",
    url: "https://feeds.reuters.com/reuters/businessNews",
    type: "rss",
    credibility: 9,
    categories: ["macro", "geopolitics"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "investing-gold",
    name: "Investing.com — Oro",
    url: "https://www.investing.com/rss/news_14.rss",
    type: "rss",
    credibility: 7,
    categories: ["geopolitics", "macro"],
    assets: ["XAU"],
    enabled: true,
  },
  {
    id: "coindesk",
    name: "CoinDesk",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    type: "rss",
    credibility: 8,
    categories: ["btc_regulation", "btc_whale"],
    assets: ["BTC"],
    enabled: true,
  },
  {
    id: "sec-press",
    name: "SEC — Comunicados",
    url: "https://www.sec.gov/news/pressreleases.rss",
    type: "rss",
    credibility: 10,
    categories: ["btc_regulation"],
    assets: ["BTC"],
    enabled: true,
  },
  {
    id: "cftc-press",
    name: "CFTC — Regulación",
    url: "https://www.cftc.gov/rss/pressreleases.xml",
    type: "rss",
    credibility: 10,
    categories: ["btc_regulation"],
    assets: ["BTC"],
    enabled: true,
  },
  {
    id: "fed-twitter",
    name: "X — @federalreserve",
    url: "https://nitter.poast.org/federalreserve/rss",
    type: "twitter_rss",
    credibility: 10,
    categories: ["fed"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "ecb-twitter",
    name: "X — @ecb",
    url: "https://nitter.poast.org/ecb/rss",
    type: "twitter_rss",
    credibility: 9,
    categories: ["fed", "macro"],
    assets: ["XAU", "BTC"],
    enabled: true,
  },
  {
    id: "whale-alert-twitter",
    name: "X — @whale_alert",
    url: "https://nitter.poast.org/whale_alert/rss",
    type: "twitter_rss",
    credibility: 8,
    categories: ["btc_whale"],
    assets: ["BTC"],
    enabled: true,
  },
];
